// Generated by Selenium IDE (cleaned)
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver

  before(async function() {
    driver = await new Builder().forBrowser('chrome').build()
  })


  it('test1', async function() {
    await driver.get("https://www.iprsm.com/")

    // Wait for Site Code input and enter "Williams"
    const siteCodeInput = await driver.wait(
      until.elementLocated(By.name("UIM_Widget_1_SiteCode")),
      10000
    )
    await siteCodeInput.sendKeys("Williams", Key.ENTER)

    // Wait for username field and enter username
    const usernameField = await driver.wait(
      until.elementLocated(By.name("UIM_Widget_1_UIM_Offset_I")),
      10000
    )
    await usernameField.sendKeys("HasanS")

    // Enter password
    const passwordField = await driver.findElement(By.name("UIM_Widget_1_UIM_Offset_K"))
    await passwordField.sendKeys("4RainDrops", Key.ENTER)

    // Wait for the dropdown
    const otherMenu = await driver.wait(
      until.elementLocated(By.name("UIM_Widget_1_OtherMenu")),
      10000
    )

    // Select "Find PRV Equip't"
    await otherMenu.findElement(By.xpath("//option[. = \"Find PRV Equip't\"]")).click()

    //await new Promise(() => {})
  })
})
